title:            Rudkerfern.net
description:      The technical toughts and ramblings of g.r.plyler
url:              http://localhost:4000
destination: ../grplyler.github.io/
signoff:          g.r.plyler
disqus_shortname: # disqus comment thread for post header options. ( leave blank if unwanted. )
facebook_appid:   # appid for like button, remove from /_includes/share.html if unwanted.
#google_analytics: # set tracking, remove from /javascripts/basic.js if unwanted.

links:
  - name:         About
    url:          /about
    external:     true
  - name:         Email
    url:          mailto:g.r.plyler@gmail.com
    external:     true
  - name:         GitHub
    url:          http://github.com/grplyler
    external:     true
highlighter:      pygments
permalink:        pretty
markdown:         redcarpet
redcarpet:
  extensions:
    - smart
